spring.application.name=budaya

spring.datasource.url=jdbc:mysql://localhost:3306/budaya
spring.datasource.username=root
spring.datasource.password=SheilaZeren4206
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Dev: matikan cache Thymeleaf agar perubahan template langsung terlihat tanpa restart
spring.thymeleaf.cache=false